### ISSUE TITLE
Upgrade to root

### ISSUE THREAD

**Issue by Clio75** [fieldrndservices/lv-libssh2#50]
Hi and thanx for the Lib. 

I have not figured how to upgrade for a user to root. after establish the connection. 
Short description ;) 
I login to UUT with keys. Then I need to become root. 
So I have tried to send (su -) and the send a password. But get no reply
![image](https://user-images.githubusercontent.com/8381796/170028286-8f04805e-ac54-4c4e-9678-b0ab35e164d9.png)

In putty I can do this without any problems. 
![image](https://user-images.githubusercontent.com/8381796/170027891-a4b6b495-b097-46b1-b334-b8bfc10d64dc.png)

I hope you can point me in the right direction :)

**Comment by volks73** [comment]
PuTTY creates an interactive terminal/shell with the remote device. This allows you to type in the password and interact with various commands by sending keystrokes to STDIN. The `su -` command, with this invocation defaults to interactive mode, where it prints a prompt, `Password: ` to the shell/terminal, most likely on STDOUT. PuTTY is continuously reading and writing from STDOUT and to STDIN, respectively.

I would suggest trying to do a read after each write, i.e. between writing `su -` and `password`. I think the prompt for the password, `Password: `, is being included in the password.

Can you try the [Read-Execute-Print-Loop with a Raspberry Pi.vi](https://github.com/fieldrndservices/libssh2-labview/blob/main/src/Examples/Read-Execute-Print-Loop%20with%20a%20Raspberry%20Pi.vi) example to execute the elevation command, `su -`. It provides a more interactive-like implementation. It will work with any remote SSH device. It does not have to be a Raspberry Pi.
